# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported

prepare_react_native_project!

# Disable React Native Firebase SPM integration.
# Firebase will be installed through CocoaPods.
$RNFirebaseDisableSPM = true

# Firebase 12 includes Swift pods. Static frameworks are the supported CocoaPods
# integration for React Native Firebase and avoid globally modularizing gRPC.
linkage = ENV.fetch('USE_FRAMEWORKS', 'static')
Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
use_frameworks! :linkage => linkage.to_sym
$RNFirebaseAsStaticFramework = true

target 'RentManagementSystem' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],

    # Absolute path to the application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # react-native-vector-icons
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
      # :ccache_enabled => true
    )

  end
end
